package tgbot

// The bot's words, in the language the settings page chose. Keyed the way
// the classic panel's tgbot strings are, so a translator who knows one knows the other.

func (b *Bot) t(key string) string {
	lang := b.config().Lang
	if d, ok := texts[lang]; ok {
		if s, ok := d[key]; ok {
			return s
		}
	}
	if s, ok := texts["en"][key]; ok {
		return s
	}
	return key
}

var texts = map[string]map[string]string{
	"en": {
		"help":              "This bot delivers data and notifications from the panel.",
		"pleaseChoose":      "Please choose:",
		"start":             "Hello %s 👋",
		"welcome":           "Welcome to <b>W-UI</b> on <b>%s</b>.",
		"statusOK":          "✅ The bot is up.",
		"getID":             "Your Telegram id: <code>%d</code>",
		"usageHint":         "Send /usage &lt;name&gt; to see a customer.",
		"unknown":           "Unknown command.",
		"restartOK":         "✅ Every tunnel was restarted.",
		"restartFailed":     "❌ Restart failed: %s",
		"areYouSure":        "⚠️ Are you sure?",
		"cancelled":         "Cancelled.",
		"resetAllDone":      "✅ Traffic reset for %d customers.",
		"resetDone":         "✅ Traffic reset.",
		"confirmResetFor":   "Reset traffic of <b>%s</b>?",
		"backupCaption":     "Database backup",
		"noBanLogs":         "No refused sign-ins recorded.",
		"banLogsTitle":      "Refused sign-ins",
		"adminCommands":     "/usage &lt;name&gt; — a customer\n/inbound &lt;name&gt; — an inbound\n/restart — restart every tunnel\n/clearall — reset all traffic\n/id — your Telegram id",
		"clientCommands":    "/usage — your plan\n/id — your Telegram id",
		"askEmail":          "Send the customer's name:",
		"askNewName":        "Send a name for the new customer:",
		"askTgID":           "Send the Telegram id for <b>%s</b>:",
		"askQuotaGB":        "Traffic limit, in GB (0 = unlimited):",
		"askExpiryDays":     "Days from now (0 = never expires):",
		"askDeviceLimit":    "Device limit:",
		"badNumber":         "That is not a number I can use.",
		"saved":             "✅ Saved.",
		"clientAdded":       "✅ Customer <b>%s</b> added with the panel's defaults.",
		"noResult":          "Nothing found.",
		"noInbounds":        "There are no inbounds.",
		"noDevices":         "No devices.",
		"noOnlines":         "Nobody is online.",
		"noDepleting":       "Nobody is running out.",
		"notLinked":         "Your Telegram id is not on any plan. Ask the operator to add it.",
		"sortedReportTitle": "Traffic, heaviest first",
		"hostname":          "Hostname", "version": "Version", "uptime": "Uptime", "cpu": "CPU", "memory": "Memory", "disk": "Disk",
		"traffic": "Traffic", "clients": "Customers", "online": "Online", "status": "Status", "usage": "Usage",
		"remaining": "Remaining", "expiry": "Expiry", "devices": "Devices", "lastOnline": "Last online", "group": "Group",
		"tgID": "Telegram id", "note": "Note",
		"active": "Active", "disabled": "Disabled", "expired": "Expired", "exhausted": "Out of traffic",
		"btnSortedReport": "📊 Sorted traffic report", "btnServerUsage": "🖥 Server usage", "btnResetAll": "♻️ Reset all traffic",
		"btnBackup": "💾 DB backup", "btnBanLogs": "🚫 Sign-in failures", "btnInbounds": "📥 Inbounds", "btnDepleteSoon": "⏳ Running out",
		"btnCommands": "📖 Commands", "btnOnlines": "🟢 Online", "btnAllClients": "👥 All customers", "btnAddClient": "➕ Add customer",
		"btnSubLinks": "🔗 Subscription", "btnIndividual": "📄 Config files", "btnQR": "🔲 QR codes", "btnClientUsage": "📊 My usage",
		"btnCancel": "❌ Cancel", "btnCancelReset": "❌ Cancel", "btnConfirmReset": "✅ Confirm reset", "btnRefresh": "🔄 Refresh",
		"btnIPLog": "📋 Device log", "btnResetTraffic": "♻️ Reset traffic", "btnLimitTraffic": "📶 Traffic limit", "btnResetExpiry": "📅 Expiry",
		"btnIPLimit": "📱 Device limit", "btnSetTgUser": "👤 Telegram id", "btnToggleEnable": "🔁 Enable / disable", "btnRemoveTgID": "🗑 Remove id",
		"btnCustom": "✏️ Custom",
		"askCustom": "Type the value:",
	},
	"fa": {
		"help":              "این ربات اطلاعات و اعلان‌های پنل را می‌فرستد.",
		"pleaseChoose":      "لطفاً انتخاب کنید:",
		"start":             "سلام %s 👋",
		"welcome":           "به <b>W-UI</b> روی <b>%s</b> خوش آمدید.",
		"statusOK":          "✅ ربات فعال است.",
		"getID":             "شناسهٔ تلگرام شما: <code>%d</code>",
		"usageHint":         "برای دیدن یک مشتری بفرستید: /usage &lt;نام&gt;",
		"unknown":           "دستور ناشناخته.",
		"restartOK":         "✅ همهٔ تانل‌ها راه‌اندازی مجدد شدند.",
		"restartFailed":     "❌ راه‌اندازی مجدد ناموفق: %s",
		"areYouSure":        "⚠️ مطمئن هستید؟",
		"cancelled":         "لغو شد.",
		"resetAllDone":      "✅ ترافیک %d مشتری بازنشانی شد.",
		"resetDone":         "✅ ترافیک بازنشانی شد.",
		"confirmResetFor":   "ترافیک <b>%s</b> بازنشانی شود؟",
		"backupCaption":     "پشتیبان پایگاه داده",
		"noBanLogs":         "ورود ناموفقی ثبت نشده است.",
		"banLogsTitle":      "ورودهای ناموفق",
		"adminCommands":     "/usage &lt;نام&gt; — یک مشتری\n/inbound &lt;نام&gt; — یک ورودی\n/restart — راه‌اندازی مجدد تانل‌ها\n/clearall — بازنشانی همهٔ ترافیک\n/id — شناسهٔ تلگرام شما",
		"clientCommands":    "/usage — پلن شما\n/id — شناسهٔ تلگرام شما",
		"askEmail":          "نام مشتری را بفرستید:",
		"askNewName":        "نامی برای مشتری جدید بفرستید:",
		"askTgID":           "شناسهٔ تلگرام را برای <b>%s</b> بفرستید:",
		"askQuotaGB":        "حجم ترافیک به گیگابایت (۰ = نامحدود):",
		"askExpiryDays":     "چند روز از امروز (۰ = بدون انقضا):",
		"askDeviceLimit":    "محدودیت دستگاه:",
		"badNumber":         "این عدد قابل استفاده نیست.",
		"saved":             "✅ ذخیره شد.",
		"clientAdded":       "✅ مشتری <b>%s</b> با پیش‌فرض‌های پنل اضافه شد.",
		"noResult":          "چیزی پیدا نشد.",
		"noInbounds":        "هیچ ورودی‌ای وجود ندارد.",
		"noDevices":         "دستگاهی نیست.",
		"noOnlines":         "کسی آنلاین نیست.",
		"noDepleting":       "کسی در حال اتمام نیست.",
		"notLinked":         "شناسهٔ تلگرام شما روی هیچ پلنی نیست. از مدیر بخواهید آن را اضافه کند.",
		"sortedReportTitle": "ترافیک، از بیشترین",
		"hostname":          "نام میزبان", "version": "نسخه", "uptime": "مدت روشن بودن", "cpu": "پردازنده", "memory": "حافظه", "disk": "دیسک",
		"traffic": "ترافیک", "clients": "مشتری‌ها", "online": "آنلاین", "status": "وضعیت", "usage": "مصرف",
		"remaining": "باقی‌مانده", "expiry": "انقضا", "devices": "دستگاه‌ها", "lastOnline": "آخرین فعالیت", "group": "گروه",
		"tgID": "شناسهٔ تلگرام", "note": "یادداشت",
		"active": "فعال", "disabled": "غیرفعال", "expired": "منقضی", "exhausted": "اتمام ترافیک",
		"btnSortedReport": "📊 گزارش ترافیک مرتب‌شده", "btnServerUsage": "🖥 وضعیت سرور", "btnResetAll": "♻️ بازنشانی همهٔ ترافیک",
		"btnBackup": "💾 پشتیبان دیتابیس", "btnBanLogs": "🚫 ورودهای ناموفق", "btnInbounds": "📥 ورودی‌ها", "btnDepleteSoon": "⏳ در حال اتمام",
		"btnCommands": "📖 دستورات", "btnOnlines": "🟢 آنلاین‌ها", "btnAllClients": "👥 همهٔ مشتری‌ها", "btnAddClient": "➕ افزودن مشتری",
		"btnSubLinks": "🔗 لینک اشتراک", "btnIndividual": "📄 فایل‌های کانفیگ", "btnQR": "🔲 کدهای QR", "btnClientUsage": "📊 مصرف من",
		"btnCancel": "❌ انصراف", "btnCancelReset": "❌ انصراف", "btnConfirmReset": "✅ تأیید بازنشانی", "btnRefresh": "🔄 به‌روزرسانی",
		"btnIPLog": "📋 گزارش دستگاه‌ها", "btnResetTraffic": "♻️ بازنشانی ترافیک", "btnLimitTraffic": "📶 محدودیت ترافیک", "btnResetExpiry": "📅 انقضا",
		"btnIPLimit": "📱 محدودیت دستگاه", "btnSetTgUser": "👤 شناسهٔ تلگرام", "btnToggleEnable": "🔁 فعال / غیرفعال", "btnRemoveTgID": "🗑 حذف شناسه",
		"btnCustom": "✏️ دلخواه",
		"askCustom": "مقدار را بنویسید:",
	},
}
